version: '3.8'

services:
  mineru-api:
    image: zxwei/mineru-api-full:v1.0.0
    container_name: mineru-api
    restart: unless-stopped
    ports:
      - "8888:8888"
      - "30000:30000"
    shm_size: '32g'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu] 