version: '3.8'

services:
  mineru-api:
    image: zxwei/mineru-api:v1.0.0  # 基础版本镜像
    container_name: mineru-api
    restart: unless-stopped
    ports:
      - "8888:8888"
    shm_size: '32g'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - mineru_data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  mineru_data:
    driver: local

networks:
  default:
    name: mineru-network
    driver: bridge 